spring.application.name=aquilesApi
graphql.servlet.mapping=/graphql
graphql.servlet.enabled=true
graphql.servlet.corsEnabled=true
graphql.servlet.corsAllowCredentials=true
graphql.servlet.corsAllowedOrigins=*
frontend.url=https://6c12-179-1-218-161.ngrok-free.app
