// Ejemplo corregido con algunas importaciones ajustadas

import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
export { Header } from '../app/components/header';  // Si el componente se llama Header y está en el archivo Header.js
import Home from './page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AquilesApp',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white text-black font-sans ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}