// layout.js
import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AquilesApp',
   icons: {
    icon: "/img/Logo-sena-green.png"
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`bg-white text-black font-sans ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
