import { Inter } from 'next/font/google';
import '@/globals.css';
import { Metadata } from 'next';
import { LoaderProvider } from '@context/LoaderContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Aquiles',
    icons: {
        icon: "/img/Logo-sena-green.png"
    },
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
    return (
        <html lang="es" className="scroll-smooth">
            <body className={`bg-white dark:bg-darkBackground text-black dark:text-white font-sans transition-colors duration-300 ${inter.className}`}>
                <LoaderProvider>
                    {children}
                </LoaderProvider>
            </body>
        </html>
    );
}