import { Inter } from 'next/font/google';
import '@/globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'AquilesApp',
    icons: {
        icon: "/img/Logo-sena-green.png"
    },
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
    return (
        <html lang="es">
            <body className={`bg-white text-black font-sans ${inter.className}`}>
                {children}
            </body>
        </html>
    );
}