server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: fabrica2023*
    key-store-type: PKCS12
    key-alias: tomcat
    trust-store: classpath:truststore.jks # Agregar esta línea
    trust-store-password: fabrica2023* # Reemplazar con la contraseña del truststore
    trust-store-type: PKCS12

spring:
  application:
    name: Aquiles

  datasource:
    url: jdbc:postgresql://localhost:5432/DBAquiles
    username: postgres
    password: "fabrica2023*"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-circular-references: true

olimpo:
  auth:
    url: https://localhost:8081/api/auth/login
    cert:
      path: classpath:olimpo_cert.pem
