<<<<<<< HEAD
=======
server:
  port: 8080

>>>>>>> keihslaDev
spring:
  application:
    name: DBAquiles

  datasource:
    url: jdbc:postgresql://localhost:5432/DBAquiles
    username: fabrica
    password: "fabrica2024*"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

<<<<<<< HEAD
  mail:
    host: smtp.gmail.com
    port: 587
    username: fosnotreply@gmail.com
    password: blquyaiclscdoufe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-circular-references: true
=======
main:
  allow-circular-references: true
>>>>>>> keihslaDev
